### PR TITLE
add documentation and test coverage

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
See https://github.com/MartinNowak/bloom/tree/2a6231c62258e1ac07fded2d753eba9651816621 for an integration. You'll need to configure Travis-CI as well (see https://travis-ci.org/MartinNowak/bloom/builds/103584684).

**Comment by MartinNowak** [comment]
There is an upcoming dub extension to allow using different ddox tools.
[allow to specify ddox tool by MartinNowak · Pull Request #702 · D-Programming-Language/dub](https://github.com/D-Programming-Language/dub/pull/702)

**Comment by biozic** [comment]
Thanks a lot for the PR and tips.
I tried to configure environment variables for Travis-CI, using a personal access token. But I must do something wrong: the build fails. The log is not helpful: it's empty.

**Comment by biozic** [comment]
OK. The empty log was an Travis-CI fault. Now I can access it [here](https://travis-ci.org/biozic/d2sqlite3/jobs/103714374). The problem is that there is an exception thrown when doveralls is running. I have no idea why.

**Comment by denizzzka** [comment]
> I have no idea why.

Try to restart CI without any changes

**Comment by MartinNowak** [comment]
You might still need to activate your repo on coveralls, that's why the [response](https://github.com/ColdenCullen/doveralls/blob/60d54f991e8370e133bb8be3a6783efbc655c254/source/doveralls/request.d#L47) contains some unexpected content.
https://coveralls.io/github/biozic/d2sqlite3

**Comment by MartinNowak** [comment]
Made a PR to improve doveralls https://github.com/ColdenCullen/doveralls/pull/14.

**Comment by biozic** [comment]
Thank you for your help. It works well now that I have activated the coveralls account :)
I will update the README file soon.

**Comment by biozic** [comment]
Concerning scod, is there a way to tweak the css from here? For example, I would like to have bullets back when there is a `<li>` in the documentation.

**Comment by MartinNowak** [comment]
> Concerning scod, is there a way to tweak the css from here? For example, I would like to have bullets back when there is a <li> in the documentation.

You could either use your own ddox theme package or for such simple things append to `docs/css/style.min.css`.
I just pushed and released (v0.1.4) a fix for `list-style-type: none`.
https://github.com/MartinNowak/scod/commit/8f36c678f0a61fe432de37d67ecc39a4022ed382

**Comment by biozic** [comment]
Thanks for the fix!

**Pull request merged**
