### PR TITLE
Add some more attributes (pure / @safe / nothrow, etc)

### PR DESCRIPTION
**Pull request by Geod24**
See each commit individually for what is being done.
The last commit (`ptrFree` removal) also explains why.

### CODE REVIEW

**Comment by Geod24** [comment]
Ping @biozic . Due to lack of activity we had to fork your repository to bpfkorea/d2sqlite3 . It would be great to keep all fixes in one place though (also since this is the registered package).

**Comment by biozic** [comment]
Yes, sorry, I don't have time for D at the moment. I guess I should look for a new maintainer for this package.

**Comment by Geod24** [comment]
@biozic : I'd be happy to help with that. Alternatively, you might consider giving ownership to https://github.com/dlang-community/ so you can benefit from having a wide range of maintainers (including myself).

**Comment by biozic** [comment]
Oups, merged too soon without testing the UnlockNotify version. `sqlite3_blocking_prepare_v2` can't be `nothrow @nogc`.

**Comment by biozic** [comment]
> @biozic : I'd be happy to help with that. Alternatively, you might consider giving ownership to https://github.com/dlang-community/ so you can benefit from having a wide range of maintainers (including myself).

I would happily give ownership to dlang-community. I'll post a message in the forum.

**Comment by Geod24** [comment]
Thanks! Any update ? I'm admin on `dlang-community`, so I can help.

**Comment by biozic** [comment]
I just really discovered the dlang-community project. It sounds like the right place. What do I have to do?

**Comment by biozic** [comment]
I'll open a new issue there.

**Comment by biozic** [comment]
Done: [Issue #46](https://github.com/dlang-community/discussions/issues/46)

**Pull request merged**
