### PR TITLE
Add with-lib and without-lib configurations to make linking sqlite3 o…

### PR DESCRIPTION
**Pull request by aldacron**
…ptional.

Implementation of ER in #15

### CODE REVIEW

**Comment by aldacron** [comment]
Hi. I'm at a critical point now with my book. I'm working on the revision for the chapter where d2sqlite3 is used. I've got a deadline in a little over 24 hours, so I'd really appreciate some feedback on whether this PR is going to be merged or not. I'd really prefer to use d2sqlite3 directly in the project, but if the PR isn't merged I'll have no choice but to register my clone with DUB under a new name and use that instead. I'd really rather not!

**Comment by denizzzka** [comment]
You can use local copy of any dub repo with dub add-local ...

**Comment by denizzzka** [comment]
Also, what is means "without lib"? d2sqlite3 can't work without this lib

**Comment by aldacron** [comment]
Yes, I'm aware of what dub add-local does. But this is for downloadable source code that goes with the book. I don't want to make readers have to type dub add-local to get it to work.

I described the problem in Issue #15. I have a configuration on Windows where I have libraries named sqlite3-dm.lib, sqlite3-ms32.lib and sqlite3-ms64.lib. I use pragmas in the source to link with the appropriate lib. When OPTLINK is the linker, the libs directive in your dub.json causes a warning, but linking succeeds. Unfortunately, libs director causes the Microsoft linker to fail with an error. In other words, it's impossible to link with sqlite3 unless it is named sqlite3.lib and is on the library path.

sqlite3 is not a system lib on Windows, so there is no standard for what it will be named or where it will be located. The without-lib configuration allows users to specify a different sqlite3 library name and avoids the errors and warnings.

**Comment by biozic** [comment]
Sorry for the delay. I am not working on my D projects at the moment. Congrats for your book!

**Comment by aldacron** [comment]
Thanks and thanks!

**Comment by denizzzka** [comment]
Thus, any "non-standard" library binding on Windows need this patch? It sounds unpleasant

**Comment by aldacron** [comment]
It's just the way the windows ecosystem works. If the MS linker didn't error out, it wouldn't be an issue, but that's the way it is. If I were developing a static binding from scratch, I would use libs-posix to specify the library, rather than different configurations, and just require the C library always be manually linked on Windows. However, since people are already using d2sqlite3, that's a breaking change. The two configurations allow people who can live with the default behavior to go on with it, but change it if they can't. Not unpleasant at all, IMO.

**Pull request merged**
