### PR TITLE
use documented unittest for module example

### PR DESCRIPTION
**Pull request by MartinNowak**
- also import d2sqlite3 in test so the example is self-contained

### CODE REVIEW

**Comment by MartinNowak** [comment]
See [Unit Tests - D Programming Language](https://dlang.org/spec/unittest.html#documented-unittests).

**Comment by MartinNowak** [comment]
Wow, I thought this might create an issue w/ the doc generation, but Travis-CI is smart enough to not leak secure variables into pull requests.

**Comment by biozic** [comment]
I always thought documented unittests were impossible at the module level...

**Comment by MartinNowak** [comment]
> I always thought documented unittests were impossible at the module level...

The comment in front of the [ModuleDeclaration](https://dlang.org/spec/module.html#ModuleDeclaration) is also just a normal documentation comment.

**Pull request merged**
