### PR TITLE
Statements keep references to their database

### PR DESCRIPTION
**Pull request by cyisfor**
Since statements must all be finalized before a database closes, the statements should keep a reference to the database object. The database object cannot be garbage collected until the statements are (or until they're all finalized, but that only happens during garbage collection for statements at the moment) since it raises an error during program shutdown and may even possibly corrupt the database, or leave open journals. With statements keeping a reference to the database object, it ensures they will be garbage collected before the database object itself.

It also allows for having an interface that only exposes prepared statements, and not the database object itself, if you really don't like carting the database object around manually or sticking it in a global variable.

### CODE REVIEW

**Comment by biozic** [comment]
Indeed, it's probably a good idea to ensure that the statements don't outlive their database connection. I suggest these modifications in your code:

1. Make `Statement._Payload.db` a `Database` field (encapsulation).
2. Change the constructor's signature to be just `Statement.this(Database db, string sql)`, and use `db.handle()` in the body.
3. Move the unit test after the body of the `Statement` struct, where the others are.
4. Remove a spurious `///`

**Comment by cyisfor** [comment]
I wasn't sure if using db.handle() was a good idea, since an accessor to the internal database handle isn't really good encapsulation either. Use of internal state should be minimized, and slapping an accessor on it won't fix that. Better to couple the database and statement code, than to couple the database, statement, and any third party code that calls db.handle()! I'll try to make those changes though.

**Comment by cyisfor** [comment]
...also wasn't sure if copying the Database object would keep the reference, the way copying the reference counted Database.Payload object did.

**Comment by biozic** [comment]
For me it's a matter of using an abstraction instead of an implementation detail. But no solution is perfect. Thanks.

**Pull request merged**
