### PR TITLE
Adjust inject so it can accept Nullable value as the first argument

### PR DESCRIPTION
**Pull request by tchaloupka**
Without this change it is not possible to inject bunch of values if the first one is of Nullable type

### CODE REVIEW

**Comment by biozic** [comment]
I wasn't sure that struct injecting was a good idea... I guess this workaround is a proof it's not.

Perhaps a better approach would be to remove struct injecting in its actual form, or have it require a UDA on the struct. This way, Nullables would work as expected.

**Comment by tchaloupka** [comment]
what about this probably less hackish way than previous version?

**Comment by biozic** [comment]
I think your first solution was better, because `inject` should work with only one argument of type `Nullable!T`. Not handling `Nullable`s as the first —and possibly only— argument was a bug.

**Comment by biozic** [comment]
Awesome ! It covers many other aspects. Thanks.

**Pull request merged**
