### PR TITLE
run tests on container infrastructure

### PR DESCRIPTION
**Pull request by MartinNowak**
- should be enough to install sqlite3 from Ubuntu precise (12.04)

### CODE REVIEW

**Comment by MartinNowak** [comment]
BTW, there is a neat feat to use `dmd`, `gdc`, and `ldc` to refer to the latest version of each compiler.

**Comment by biozic** [comment]
Thanks. The problem is that old Ubuntu releases have a version of sqlite (< 3.8.7) that misses some functions I happen to use in the unit tests.

**Comment by biozic** [comment]
Actually it's more than that. The sqlite version coming with Ubuntu precise lack the `sqlite3_xxx64` functions.

**Comment by MartinNowak** [comment]
> Actually it's more than that. The sqlite version coming with Ubuntu precise lack the sqlite3_xxx64 functions.

Why are they needed? Makes it more difficult to deploy anything using d2sqlite3. Could they be turned into optional dependencies?
Let's keep the Travis config as is for now.

**Comment by biozic** [comment]
They aren't absolutely needed, but they're more up to date, and some people apparently rely on them. I could probably add some version blocks to account for old versions of Sqlite. But the fact is that Sqlite is so easy to download, compile and link into any project, I considered it wasn't worth maintaining backward compatibility. Moreover, recent versions of Sqlite have many improvements feature-wise and performance-wise...
Yet, I wish I could add the possibility to ship Sqlite with the library, ideally compiled from source. I still need to find out how to use dub for this, and how to do it on Windows. Maybe I should have a look at how it's done in Phobos for zlib.

**Pull request closed without merging**
